name: main

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
      #  with:
      #    # Run the below on your first attempt, then visit the URL and get the recommended settings
      #    # egress-policy: audit
      #    disable-sudo: true
      #    egress-policy: block
      #    allowed-endpoints: >
      #      api.github.com:443
      #      github.com:443
      #      registry.npmjs.org:443

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run StandardLint
        uses: mikaelvesavuori/standardlint-action@v1.0.5
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Run
        run: npm start

      - uses: advanced-security/sbom-generator-action@v0.0.1
        id: sbom
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/upload-artifact@v3.1.0
        with:
          path: ${{steps.sbom.outputs.fileName }}
          name: "SBOM"

  deployment:
    needs: build
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy
        run: echo "Deploying..."
